Split



np.hsplit() # for columns  horizontally

np.vsplit() # for rows vertically 

In [69]:
import numpy as np 


data = np.arange(1,101).reshape(10,10)
print(data)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [75]:
np.random.seed(42)
np.random.shuffle(data)
print(data)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 91  92  93  94  95  96  97  98  99 100]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 81  82  83  84  85  86  87  88  89  90]]


In [ ]:
train_split = int(0.7 * len(data))
val_split = int(0.85 * len(data))




10

In [48]:
train ,val, test = np.split(data, [train_split, val_split])

train 

val

test

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [53]:
np.random.seed(10)

data = np.random.randint(1,101, size=(120,6))
data.shape

data

array([[ 10,  16,  65,  29,  90,  94],
       [ 30,   9,  74,   1,  41,  37],
       [ 17,  12,  55,  89,  63,  34],
       [ 73,  79,  50,  52,  55,  78],
       [ 70,  14,  26,  14,  93,  87],
       [ 31,  31,  90,  13,  66,  32],
       [ 58,  37,  28,  19,  94,  78],
       [ 23,  24,  95,  12,  29,  75],
       [ 89,  10,  16,  19,  81,  72],
       [ 89,  12,  18,  47,   8,  76],
       [ 29,  34,  85,  97,  89,  45],
       [  6,   5,  72,  89,  89,  51],
       [ 55,  35,  16,  78,  89,  16],
       [  7,  86,  23,  12,  13,  93],
       [ 97,  63,  58,  80,  43,  58],
       [ 98,  51,  46,  41,  90,  74],
       [ 38,   1,  19,  24,   4,  30],
       [ 17,  85,  83,  15,  52,  80],
       [ 18,  51,  54,  26,  49,  18],
       [ 33,  82,  81,  42,  91,  13],
       [ 31,  82,  18,  17,   1,  32],
       [ 74,  65,  39,  23,  97,  67],
       [ 68,  63,  96, 100,  28,  83],
       [ 63,  78,  49,  94,  76,  87],
       [ 38,  12,  22,  34,  96,  44],
       [ 89,  97,  74,  4

In [56]:
np.random.shuffle(data)
data

array([[ 18,  51,  54,  26,  49,  18],
       [ 67,  38,  32,  57,  82,  88],
       [ 23,  24,  95,  12,  29,  75],
       [ 98,  51,  46,  41,  90,  74],
       [ 21,  10,  41,  17,  76,  40],
       [ 82,  11,  62,  24,   2,  29],
       [ 61,   4,  51,  60,  35,  22],
       [ 89,  12,  18,  47,   8,  76],
       [ 98,  98,  99,  13,  83,  78],
       [ 78,  19,  28,  84,  38,  72],
       [ 66,  14,  76,  53,   6,  94],
       [ 26,  64,  60,   3,  31,  18],
       [ 43,   1,  89,  55,  57,  37],
       [ 71,  98,   6,  73,  30,  20],
       [ 14,  42,  34,   5,  88,  95],
       [ 87,  76,  73,  89,  27,  81],
       [  4,  49,  77,  77,  59,  66],
       [ 39,  95,   3,  37,  75,  57],
       [ 74,  52,  78,  14,  98,   8],
       [ 89,  16,  56,   7,  45,  10],
       [ 73,  79,  50,  52,  55,  78],
       [ 72,   9,  86,  73,  29,  31],
       [ 15,  36,  85,  38,  63,  68],
       [ 60,  71,  64,  87,  30,  72],
       [ 60,  21,  32,  90,   1,  97],
       [ 30,   9,  74,   

In [ ]:
train_split = int(0.7 * len(data))
val_split = int(0.85 * len(data)) 
train ,val, test = np.split(data, [train_split, val_split])


In [67]:
len(train), len(val), len(test)

(84, 18, 18)