Array Creation

Create a 1D NumPy array with numbers from 10 to 100 (step 10).

Create a 2D  matrix.

In [33]:
import numpy as np
#1D
arr = np.zeros(10,dtype=int)
for i in range (len(arr)):
	arr[i] = (i + 1) * 10
print(arr)
#2D
arrD= np.array([[1,2,3],[4,5,6]])
arrD.shape

[ 10  20  30  40  50  60  70  80  90 100]


(2, 3)

Given arr = np.array([5, 10, 15, 20, 25]):

Find its mean, median, standard deviation.

Multiply every element by 3.

Filter values greater than 15.

In [34]:
#mean
arr1 = np.array([5,10,15,20,25])
count=arr1.size
sum=0
for i in range (len(arr1)):
	sum += arr1[i]
    
mean = sum//count
print("The mean is")
print(mean)
#median
mid = count // 2
median = arr1[mid]
print("The median is")
print(median)
# multiply by 3 
for i in range (len(arr1)):
	arr1[i] = arr1[i] * 3
print("Array x by 3:")
print(arr1)
#filter greater than 15
arr2 = np.array([5,10,15,20,25])
indices = [] 
for i in range (len(arr2)):
    if arr2[i] <= 15:
        indices.append(i)
        
arr2= np.delete(arr2,indices)
print("Filtered array:")
print(arr2)

The mean is
15
The median is
15
Array x by 3:
[15 30 45 60 75]
Filtered array:
[20 25]


Make one matrix and Sort the matrix row-wise and column-wise.

In [35]:
arr3= np.array([[3,2,1],[6,5,4]])
arr3 = np.sort(arr3)
print("sorted array")
print(arr3)

sorted array
[[1 2 3]
 [4 5 6]]


Load & Explore

Load the CSV using Pandas.

Show first 5 rows, shape, and column names.

In [36]:
#first five rows
import pandas as pd
df = pd.read_csv("Iris 2.csv")
df.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [37]:
#shape
df.shape

(150, 6)

In [38]:
#return column names
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [39]:
#or 
df.columns.tolist()


['Id',
 'SepalLengthCm',
 'SepalWidthCm',
 'PetalLengthCm',
 'PetalWidthCm',
 'Species']


Optional*

Selection & Filtering

Select only the Name and Marks columns.

Show students with Marks > 80.

Show students in Grade "A".

In [ ]:
#NAMES N COLUMNS
ef = pd.read_csv("students.csv")
print(ef[["Name", "Marks"]])

   Name  Marks
0   Ali     85
1  Sara     72
2  Omar     90
3  Hina     60


In [ ]:
#Stu w grade A
reqstudents =  ef[ef["Grade"] == 'A']
print(reqstudents[["Name"]])


   Name
0   Ali
2  Omar


In [ ]:
#Marks more than 80
req2 = ef [ef ["Marks"] > 80 ]
print(req2["Name"])

0     Ali
2    Omar
Name: Name, dtype: object
